# Dependencies
#markdown:     rdiscount
#pygments:     true

# Permalinks
#permalink:    pretty

# Server
source:       ./docs
destination:  ./_site
port:         9001
url:          http://localhost:9001
